import type { ExportPreset } from '../types/edify';

export const effectPresets = [
  'Blur',
  'Sharpen',
  'Noise',
  'Vignette',
  'RGB Shift',
  'Glow',
  'Shake',
  'Zoom Punch',
  'Flicker',
  'Black and White',
  'Contrast Boost',
  'Saturation Boost',
  'Cinematic Cool Tone',
  'Warm Tone',
  'Gaming Highlight',
  'Film Grain',
  'Lens Blur',
  'Edge Glow',
  'Dream Bloom',
  'VHS Glitch',
  'Speed Lines',
  'Light Leak',
  'Duotone Pop',
  'Shadow Lift',
  'Highlight Roll',
  'Pixel Sort',
  'Motion Blur',
  'Cinematic Bars',
  'Film Halation',
  'Soft Beauty Diffusion',
  'Luxury Product Shine',
  'Studio Clean HDR',
  'Midnight Teal Grade',
  'Black Pro Mist',
  'Trailer Impact Grade',
  'Cyber HUD Pulse',
  'Rank Up Flash',
  'Speed Ramp Shock',
  'Glitch Scan Burst',
  'Diamond Skin Bloom',
  'Creator Detail Pop',
  'Prism Split',
  'Clean Beauty Grade',
  'Teal Orange Deluxe',
  'Festival Film Print'
];

export const creatorEssentialsPresets = [
  'Clean Creator',
  'Soft Film',
  'Light Leak',
  'Lower Third',
  'Whoosh Sweep',
  'Smooth Zoom',
  'Creator Glow',
  'Subtitle Pop',
  'Short Viral Hook',
  'Daily Vlog Pack',
  'Travel Reel Starter',
  'Podcast Clip Stack',
  'Reaction Cut Kit',
  'Storytime Captions',
  'Beauty Soft Glow',
  'Fashion Label Pack',
  'Product Reveal Pack',
  'Luxury Ad Starter',
  'Gaming Neon Flash',
  'Streamer Intro Pack',
  'Rank Up Motion',
  'Fast Meme Captions',
  'Clean Tutorial Pack',
  'Minimal Promo Card',
  'Social CTA Overlay',
  'Swipe Up Prompt',
  'Comment Bubble Pack',
  'Shorts End Card',
  'Warm Vlog Grade',
  'LoFi Mood Pack',
  'Photo Dump Intro',
  'Travel Stamp Overlay',
  'Food Reel Starter',
  'GRWM Clean Pack',
  'Podcast Lower Third',
  'Studio Notes Card',
  'Quick Zoom Titles',
  'Impact Flash Hits',
  'Hook Generator Pack',
  'Auto Beat Kit',
  'Creator Safe Captions',
  'Brand Reveal Card',
  'Minimal Glass Captions',
  'Cinematic Tease Pack',
  'Trailer Title Starter',
  'Voiceover Caption Kit',
  'Moodboard Overlay',
  'Chill Cut Starter',
  'Street Neon Pack',
  'Luxury Product Labels',
  'Travel Map Card',
  'Beauty Routine Captions',
  'Tech Review Pack',
  'Short Review CTA',
  'Client Preview Frame',
  'Promo Countdown Pack',
  'Final Hook Ender'
];

export const transitionPresets = [
  'Fade',
  'Dissolve',
  'Whip Pan',
  'Zoom Punch',
  'Glitch Portal',
  'Film Burn',
  'Glass Swipe',
  'Camera Roll',
  'Luma Dream Dissolve',
  'Shockwave Cut',
  'Neon Speed Tunnel',
  'Anamorphic Blur Wipe',
  'Mask Reveal',
  'Pixel Sort Cut',
  'VHS Tear',
  'Flash Frame',
  'Ink Spread',
  'Split Slide',
  'Liquid Warp',
  'Prism Refraction',
  'Parallax Push',
  'Smooth Zoom',
  'Slide',
  'Push',
  'Blur',
  'Spin',
  'Whip',
  'Camera Whip',
  'Glitch',
  'Glitch Warp',
  'Flash',
  'Burn Flash',
  'Light Sweep',
  'Luma Fade',
  'Split Slide',
  'Smooth Cross Zoom',
  'Velocity Push',
  'Aero Slide',
  'Flash Pop',
  'Clean Dip to White',
  'Dream Blur Dissolve',
  'Cinematic Dip to Black',
  'Swipe Flow',
  'Edge Light Wipe',
  'Luxury Glass Drift',
  'Prism Burst',
  'Diamond Split',
  'Soft Bloom Dissolve',
  'Glow Flash Cut',
  'Trailer Slam Flash',
  'Motion Smear',
  'Fast Tunnel Rush',
  'Parallax Lift',
  'Parallax Drop',
  'Camera Snap',
  'Viewport Pull',
  'Speed Ramp Wipe',
  'Analog Tear',
  'Tape Distort',
  'Retro TV Blink',
  'HUD Scan Jump',
  'Signal Break',
  'Liquid Chrome Warp',
  'Mirror Split',
  'Dual Panel Slide',
  'Vertical Push',
  'Horizontal Push',
  'Mask Circle Burst',
  'Mask Rectangle Reveal',
  'Ink Bloom',
  'Ink Ripple',
  'Glass Beam',
  'Light Leak Sweep',
  'Heatwave Warp',
  'Dream Portal',
  'Soft Luma Wash',
  'Anamorphic Streak Wipe',
  'Cinematic Gate Flash',
  'Viral Pop Cut',
  'Creator Snap Zoom',
  'Rank Up Portal',
  'Game Win Flash',
  'Luxury Swipe',
  'Beauty Blur Flow',
  'Product Focus Pull',
  'Reel Scroll Flip',
  'Story Swipe Up',
  'Photo Card Flip',
  'Paper Tear Cut',
  'Monochrome Flash',
  'Color Burst Dissolve',
  'Neon Refraction',
  'Impact Whip Pro'
];

export const textPresets = [
  'Subtitle',
  'Title',
  'Lower Third',
  'Gaming Edit',
  'Cinematic Title',
  'Neon Title',
  'Creator Pop Subtitle',
  'Diamond Caption',
  'Product Callout Pro',
  'Luxury Lower Third',
  'Trailer Impact Title',
  'Anamorphic Title Pro',
  'Film Festival Card',
  'Rank Up Caption',
  'Killfeed Pro Label',
  'Neon HUD Title',
  'Stream Alert Text',
  'Podcast Title Bar',
  'Review Quote Card',
  'Travel Stamp Title',
  'Beauty Routine Tag',
  'Fashion Drop Label',
  'Daily Vlog Opener',
  'Hook Opener Text',
  'Swipe Up CTA',
  'Comment Bubble Title',
  'Episode Chapter Card',
  'Fact Callout',
  'Minimal Brand Card',
  'Bold Reel Title',
  'Soft Story Caption',
  'Luxury Price Tag',
  'Product Feature Box',
  'Countdown Title',
  'Final CTA'
];

export const textAnimationPresets = [
  'Fade In',
  'Fade Out',
  'Cinematic Fade',
  'Slide Up',
  'Slide Down',
  'Slide Left',
  'Slide Right',
  'Pop In',
  'Bounce In',
  'Zoom In',
  'Zoom Out',
  'Blur Reveal',
  'Typewriter',
  'Karaoke Glow',
  'Neon Flicker',
  'Glitch Text',
  'Wave Text',
  'Letter Spacing',
  'Lower Third Sweep',
  'Word Punch',
  'Spin In',
  'Skew Snap',
  'Exit Drop',
  'Exit Blur',
  'Exit Slide Left',
  'Exit Slide Right',
  'Soft Rise',
  'Soft Drop',
  'Fast Pop In',
  'Impact Pop',
  'Elastic Punch',
  'Bounce Drop',
  'Micro Shake In',
  'Flash Type',
  'Blur Fade Up',
  'Blur Fade Down',
  'Swipe Reveal',
  'Mask Reveal Circle',
  'Mask Reveal Bar',
  'Word Highlight',
  'Word Highlight Alt',
  'Kinetic Subtitle',
  'Kinetic Subtitle 2',
  'TikTok Bounce',
  'TikTok Pop',
  'CapCut Glow Pop',
  'CapCut Word Pulse',
  'Beat Flash Text',
  'Beat Scale Pulse',
  'Ranking Flash',
  'HUD Scan In',
  'HUD Flicker',
  'Digital Drift',
  'VHS Text Tear',
  'Split Text Slide',
  'Prism Text Split',
  'Glass Shine Pass',
  'Luxury Shine',
  'Diamond Pulse',
  'Soft Bloom Text',
  'Film Credit Rise',
  'Film Credit Drift',
  'Anamorphic Sweep',
  'Trailer Hit In',
  'Trailer Hit Out',
  'Cinematic Float',
  'Cinematic Collapse',
  'Lower Third Swipe',
  'Lower Third Lift',
  'Comment Bubble Pop',
  'Emoji Bounce',
  'Creator Headline',
  'Product Price Pulse',
  'Review Quote Reveal',
  'Podcast Chapter Slide',
  'Type Burst',
  'Fast Type On',
  'Slow Type On',
  'Cursor Typewriter',
  'Neon Pulse',
  'Neon Shock',
  'Glitch Entrance',
  'Glitch Exit',
  'Wave Drift',
  'Letter Burst',
  'Tracking Fade',
  'Strobe Pop',
  'Whip Text',
  'Velocity Text',
  'Flash Card In',
  'Flash Card Out',
  'Orbit In',
  'Orbit Out',
  'Parallax Text',
  'Depth Lift',
  'Depth Drop',
  'Outline Reveal',
  'Outline Glow',
  'Subtitle Snap',
  'Subtitle Bounce',
  'Story Card Slide',
  'Reel Title Slam',
  'Final CTA Pulse',
  'Exit Whip Left',
  'Exit Whip Right',
  'Exit Scale Down',
  'Exit Fade Up',
  'Exit Fade Down'
];

export const filterPresets = [
  'Kodak Night',
  'Blade Blue',
  'Chrome Pop',
  'Soft Film',
  'Warm Studio',
  'Deep Mono',
  'Clean Creator',
  'Hyperlight',
  'Teal Orange Deluxe',
  'Noir Luxe',
  'Portra Glow Pro',
  'Clean Beauty Grade',
  'E-Sport Neon Grade',
  'Cyber Contrast LUT',
  'Luxury Ad Film',
  'Festival Film Print',
  'Midnight Teal',
  'Sunset Creator',
  'Cloudy Film',
  'Rich Contrast',
  'Soft Skin Light',
  'Warm Product',
  'Cool Trailer',
  'Street Neon',
  'Pearl Mono'
];

export type PremiumEffectPreset = {
  name: string;
  pack: 'Cinematic Pro' | 'Gaming Pro' | 'Creator Pro';
  description: string;
};

export const premiumEffectPresets: PremiumEffectPreset[] = [
  { name: 'AI Aura Glow', pack: 'Creator Pro', description: 'Soft subject glow with premium creator polish.' },
  { name: 'Prism Split', pack: 'Creator Pro', description: 'Glass-like RGB refraction for music edits.' },
  { name: 'Film Halation', pack: 'Cinematic Pro', description: 'Warm highlight bloom inspired by cinema scans.' },
  { name: 'Cinematic Fog', pack: 'Cinematic Pro', description: 'Depth haze and muted contrast for moody shots.' },
  { name: 'Luxury Skin Light', pack: 'Creator Pro', description: 'Clean soft light for face and product shots.' },
  { name: 'Hyper Zoom Warp', pack: 'Gaming Pro', description: 'Punchy speed ramp accent for action cuts.' },
  { name: 'Neon Edge Pulse', pack: 'Gaming Pro', description: 'Animated edge glow look for high energy edits.' },
  { name: 'Golden Hour Pro', pack: 'Cinematic Pro', description: 'Warm premium sunlight tone with lifted shadows.' },
  { name: 'Anamorphic Streak', pack: 'Cinematic Pro', description: 'Horizontal lens streaks and deep contrast.' },
  { name: 'Viral Velocity Shake', pack: 'Gaming Pro', description: 'Creator-style shake and motion intensity.' },
  { name: 'Dream Lens Pro', pack: 'Creator Pro', description: 'Glossy bloom and gentle soft-focus finish.' },
  { name: 'Studio Clean HDR', pack: 'Creator Pro', description: 'Crisp high dynamic range product look.' },
  { name: 'Diamond Skin Bloom', pack: 'Creator Pro', description: 'Glossy creator beauty light with controlled highlights.' },
  { name: 'Luxury Product Shine', pack: 'Creator Pro', description: 'Premium reflective shine for products and fashion edits.' },
  { name: 'Soft Beauty Diffusion', pack: 'Creator Pro', description: 'Smooth creator diffusion with glow and gentle contrast.' },
  { name: 'Creator Detail Pop', pack: 'Creator Pro', description: 'Local contrast and clarity for sharp social content.' },
  { name: 'Midnight Teal Grade', pack: 'Cinematic Pro', description: 'Deep teal shadows and controlled cinematic highlights.' },
  { name: '35mm Dust Glow', pack: 'Cinematic Pro', description: 'Film dust, halation, and soft gate-weave inspired finish.' },
  { name: 'Black Pro Mist', pack: 'Cinematic Pro', description: 'Muted contrast with premium soft highlight rolloff.' },
  { name: 'Trailer Impact Grade', pack: 'Cinematic Pro', description: 'Dense shadows, punchy contrast, and dramatic trailer tone.' },
  { name: 'Cyber HUD Pulse', pack: 'Gaming Pro', description: 'Futuristic UI pulse and edge glow for gaming highlights.' },
  { name: 'Rank Up Flash', pack: 'Gaming Pro', description: 'High-energy victory flash with neon contrast.' },
  { name: 'Speed Ramp Shock', pack: 'Gaming Pro', description: 'Premium motion shock for ramped kills, wins, and reveals.' },
  { name: 'Glitch Scan Burst', pack: 'Gaming Pro', description: 'Scanline burst with RGB displacement and noise.' },
  { name: 'Luxury Mirror Bloom', pack: 'Creator Pro', description: 'Reflective premium bloom for fashion and product edits.' },
  { name: 'Velvet Portrait Lift', pack: 'Creator Pro', description: 'Soft portrait lift with smooth skin and luminous midtones.' },
  { name: 'Runway Edge Light', pack: 'Creator Pro', description: 'Editorial side light for fashion reels and brand shots.' },
  { name: 'Cine Contrast Lift', pack: 'Cinematic Pro', description: 'Dense blacks and controlled highlight lift for filmic scenes.' },
  { name: 'Silver Mist Print', pack: 'Cinematic Pro', description: 'Premium mist diffusion with silver-rich monochrome feel.' },
  { name: 'Midnight Scope HDR', pack: 'Cinematic Pro', description: 'Deep scope-driven grade with polished highlight detail.' },
  { name: 'Arena Impact Pulse', pack: 'Gaming Pro', description: 'Hard-hit pulse built for action edits and beat drops.' },
  { name: 'Portal Velocity FX', pack: 'Gaming Pro', description: 'High-speed tunnel, glow, and chromatic warp combo.' }
];

export const premiumFilterPresets: PremiumEffectPreset[] = [
  { name: 'Teal Orange Deluxe', pack: 'Cinematic Pro', description: 'Premium blockbuster contrast with refined skin tones.' },
  { name: 'Noir Luxe', pack: 'Cinematic Pro', description: 'Deep monochrome with soft highlight rolloff.' },
  { name: 'Portra Glow Pro', pack: 'Creator Pro', description: 'Warm film color with flattering creator glow.' },
  { name: 'Clean Beauty Grade', pack: 'Creator Pro', description: 'Smooth high-end creator grade for face and product shots.' },
  { name: 'E-Sport Neon Grade', pack: 'Gaming Pro', description: 'High contrast cyan and green gaming highlight look.' },
  { name: 'Cyber Contrast LUT', pack: 'Gaming Pro', description: 'Punchy cyber color preset with crisp blacks.' },
  { name: 'Luxury Ad Film', pack: 'Creator Pro', description: 'Premium commercial tone with elegant saturation.' },
  { name: 'Festival Film Print', pack: 'Cinematic Pro', description: 'Muted festival print with dense shadows.' },
  { name: 'Pearl Skin Soft', pack: 'Creator Pro', description: 'Bright skin tone protection with soft creator contrast.' },
  { name: 'Modern Storefront', pack: 'Creator Pro', description: 'Clean commercial look for product launches and ads.' },
  { name: 'Cold Trailer Steel', pack: 'Cinematic Pro', description: 'Cool steel blue grade with restrained highlight bloom.' },
  { name: 'Dusty 35 Print', pack: 'Cinematic Pro', description: 'Textured 35mm print with subtle gate and dust feel.' },
  { name: 'Victory Neon Green', pack: 'Gaming Pro', description: 'Bright rank-up contrast for montage moments.' },
  { name: 'RGB Arena Split', pack: 'Gaming Pro', description: 'Hyper-saturated RGB split look for esports edits.' }
];

export const premiumTransitionPresets: PremiumEffectPreset[] = [
  { name: 'VIP Liquid Zoom', pack: 'Creator Pro', description: 'Smooth liquid zoom transition for creator edits.' },
  { name: 'VIP Glass Swipe', pack: 'Creator Pro', description: 'Polished glass panel swipe with soft reflections.' },
  { name: 'VIP Camera Roll', pack: 'Creator Pro', description: 'Phone-camera roll transition with subtle blur.' },
  { name: 'VIP Mask Reveal', pack: 'Creator Pro', description: 'Clean masked reveal for product and title cuts.' },
  { name: 'Cinema Match Cut', pack: 'Cinematic Pro', description: 'Elegant film match cut with contrast and gate feel.' },
  { name: 'Anamorphic Blur Wipe', pack: 'Cinematic Pro', description: 'Wide lens blur wipe with cinematic streaks.' },
  { name: 'Film Burn Deluxe', pack: 'Cinematic Pro', description: 'Premium warm film burn with light leaks.' },
  { name: 'Luma Dream Dissolve', pack: 'Cinematic Pro', description: 'Soft luma dissolve for dramatic sequence changes.' },
  { name: 'Whip Pan Pro', pack: 'Gaming Pro', description: 'Fast whip pan with motion blur and punch.' },
  { name: 'Glitch Portal', pack: 'Gaming Pro', description: 'RGB portal jump for gaming edits.' },
  { name: 'Shockwave Cut', pack: 'Gaming Pro', description: 'Impact wave transition for beat hits and eliminations.' },
  { name: 'Neon Speed Tunnel', pack: 'Gaming Pro', description: 'Fast tunnel zoom with electric streaks.' },
  { name: 'Glass Beam Deluxe', pack: 'Creator Pro', description: 'Premium refracted beam wipe with glossy reflections.' },
  { name: 'Beauty Blur Flow', pack: 'Creator Pro', description: 'Smooth creator blur flow for GRWM and beauty edits.' },
  { name: 'Luxury Mirror Swipe', pack: 'Creator Pro', description: 'Reflective editorial swipe for premium product cuts.' },
  { name: 'Gate Flash Deluxe', pack: 'Cinematic Pro', description: 'Film-gate flash with polished density and rolloff.' },
  { name: 'Prism Refraction Pro', pack: 'Cinematic Pro', description: 'High-end refraction wipe with cinematic color split.' },
  { name: 'Heatwave Warp Pro', pack: 'Cinematic Pro', description: 'Fluid thermal warp between moody cinematic shots.' },
  { name: 'Rank Portal Pro', pack: 'Gaming Pro', description: 'Victory portal cut for big gaming beats.' },
  { name: 'Impact Whip Deluxe', pack: 'Gaming Pro', description: 'Heavy blur whip with punch flash and tilt.' }
];

export const premiumTextPresets: PremiumEffectPreset[] = [
  { name: 'Luxury Lower Third', pack: 'Creator Pro', description: 'Minimal creator lower third with premium glass styling.' },
  { name: 'Diamond Caption', pack: 'Creator Pro', description: 'Glossy subtitle style with soft glow and strong readability.' },
  { name: 'Creator Pop Subtitle', pack: 'Creator Pro', description: 'Bold social subtitle with punchy highlight color.' },
  { name: 'Product Callout Pro', pack: 'Creator Pro', description: 'Elegant product label with clean premium contrast.' },
  { name: 'Cinematic Credit Roll', pack: 'Cinematic Pro', description: 'Film title typography for intros and credits.' },
  { name: 'Anamorphic Title Pro', pack: 'Cinematic Pro', description: 'Wide cinematic title with blue lens streak energy.' },
  { name: 'Trailer Impact Title', pack: 'Cinematic Pro', description: 'Huge dramatic title for trailer moments and reveals.' },
  { name: 'Film Festival Card', pack: 'Cinematic Pro', description: 'Premium festival-style title card for short films.' },
  { name: 'Rank Up Caption', pack: 'Gaming Pro', description: 'Gaming caption with neon edge and impact weight.' },
  { name: 'Killfeed Pro Label', pack: 'Gaming Pro', description: 'Fast HUD-inspired label for highlights and wins.' },
  { name: 'Neon HUD Title', pack: 'Gaming Pro', description: 'Futuristic title with electric frame and glow.' },
  { name: 'Stream Alert Text', pack: 'Gaming Pro', description: 'Creator stream title with energetic pop and contrast.' },
  { name: 'Luxury Price Card', pack: 'Creator Pro', description: 'Premium price label for product and brand content.' },
  { name: 'Creator CTA Panel', pack: 'Creator Pro', description: 'Clean premium call-to-action for shorts and reels.' },
  { name: 'Festival Opening Card', pack: 'Cinematic Pro', description: 'Polished opening card with restrained film elegance.' },
  { name: 'Scene Chapter Slate', pack: 'Cinematic Pro', description: 'Chapter style slate for narrative and documentary cuts.' },
  { name: 'Combo Finish Banner', pack: 'Gaming Pro', description: 'High-energy finish banner for gaming moments.' },
  { name: 'Arena Countdown HUD', pack: 'Gaming Pro', description: 'Esports HUD countdown and score text system.' }
];

export const premiumTextAnimationPresets: PremiumEffectPreset[] = [
  { name: 'VIP Type Burst', pack: 'Creator Pro', description: 'Fast creator type-on burst with glow.' },
  { name: 'Glossy Word Pop', pack: 'Creator Pro', description: 'Premium word-by-word pop for shorts captions.' },
  { name: 'Caption Bounce Pro', pack: 'Creator Pro', description: 'Smooth bounce caption entrance with clean overshoot.' },
  { name: 'Diamond Reveal', pack: 'Creator Pro', description: 'Soft shine reveal for creator titles.' },
  { name: 'Cinematic Drift In', pack: 'Cinematic Pro', description: 'Slow film title drift with fade and tracking.' },
  { name: 'Anamorphic Sweep Text', pack: 'Cinematic Pro', description: 'Lens streak sweep across title text.' },
  { name: 'Trailer Slam', pack: 'Cinematic Pro', description: 'Heavy title impact for dramatic moments.' },
  { name: 'Credit Fade Deluxe', pack: 'Cinematic Pro', description: 'Elegant credits fade with polished spacing.' },
  { name: 'HUD Glitch In', pack: 'Gaming Pro', description: 'Neon HUD glitch entrance for gaming edits.' },
  { name: 'Rank Flash Text', pack: 'Gaming Pro', description: 'Victory rank flash animation with glow.' },
  { name: 'Combo Counter Pop', pack: 'Gaming Pro', description: 'Arcade-style counter punch animation.' },
  { name: 'Cyber Scan Reveal', pack: 'Gaming Pro', description: 'Scanline reveal for futuristic text.' },
  { name: 'Luxury Shine Pass', pack: 'Creator Pro', description: 'Glossy pass across creator and product text.' },
  { name: 'Creator Bounce Stack', pack: 'Creator Pro', description: 'Short-form stacked pop animation for captions and hooks.' },
  { name: 'Festival Float In', pack: 'Cinematic Pro', description: 'Elegant slow float with premium fade timing.' },
  { name: 'Scene Break Slam', pack: 'Cinematic Pro', description: 'Big dramatic slam for chapters and reveals.' },
  { name: 'Arena Flash Count', pack: 'Gaming Pro', description: 'HUD count-up flash for score and rank moments.' },
  { name: 'Portal Text Jump', pack: 'Gaming Pro', description: 'Digital portal jump entrance for heavy gaming edits.' }
];

export const premiumCaptionPresets: PremiumEffectPreset[] = [
  { name: 'Auto Viral Captions Pro', pack: 'Creator Pro', description: 'Bold animated subtitles for short-form edits.' },
  { name: 'Karaoke Word Highlight Pro', pack: 'Creator Pro', description: 'Word-by-word highlight captions with glow.' },
  { name: 'Podcast Subtitle Clean', pack: 'Creator Pro', description: 'Readable long-form captions with minimal framing.' },
  { name: 'Cinematic Burn-In Captions', pack: 'Cinematic Pro', description: 'Film-style captions ready for exports.' },
  { name: 'Documentary Lower Captions', pack: 'Cinematic Pro', description: 'Clean documentary caption bar and spacing.' },
  { name: 'Gaming Callout Captions', pack: 'Gaming Pro', description: 'Fast callout captions for highlights and wins.' },
  { name: 'Streamer Chat Captions', pack: 'Gaming Pro', description: 'Chat-like subtitle blocks for stream edits.' },
  { name: 'Luxury Product Captions', pack: 'Creator Pro', description: 'Premium product caption style with soft box.' },
  { name: 'Viral Hook Captions', pack: 'Creator Pro', description: 'Aggressive hook-ready captions built for short loops.' },
  { name: 'Elegant Reel Captions', pack: 'Creator Pro', description: 'Soft fashion caption system with polished spacing.' },
  { name: 'Scene Dialogue Captions', pack: 'Cinematic Pro', description: 'Clean dialogue treatment for cinematic sequences.' },
  { name: 'Trailer Quote Captions', pack: 'Cinematic Pro', description: 'Bold quote burn-ins for teaser and trailer beats.' },
  { name: 'Rank Up Captions Pro', pack: 'Gaming Pro', description: 'Animated win captions with neon emphasis and punch.' },
  { name: 'Clip Reaction Captions', pack: 'Gaming Pro', description: 'Fast reactive captions for meme, reaction, and stream content.' }
];

export const exportPresets: ExportPreset[] = [
  {
    id: 'shorts',
    label: 'Shorts / TikTok',
    resolution: '1080 x 1920',
    bitrate: '16 Mbps',
    fps: 30,
    quality: 'High'
  },
  {
    id: '720p',
    label: '720p Social Draft',
    resolution: '1280 x 720',
    bitrate: '8 Mbps',
    fps: 30,
    quality: 'Medium'
  },
  {
    id: '1080p',
    label: 'YouTube 1080p',
    resolution: '1920 x 1080',
    bitrate: '16 Mbps',
    fps: 30,
    quality: 'High'
  },
  {
    id: '1440p',
    label: '1440p Studio',
    resolution: '2560 x 1440',
    bitrate: '35 Mbps',
    fps: 60,
    quality: 'High'
  },
  {
    id: 'gaming-ultra',
    label: 'Gaming Ultra',
    resolution: '2560 x 1440',
    bitrate: '50 Mbps',
    fps: 60,
    quality: 'Ultra'
  },
  {
    id: '4k',
    label: 'YouTube 4K Premium',
    resolution: '3840 x 2160',
    bitrate: '70 Mbps',
    fps: 60,
    quality: 'Ultra'
  },
  {
    id: 'cinema-master',
    label: 'Cinematic Master',
    resolution: '3840 x 2160',
    bitrate: '70 Mbps',
    fps: 24,
    quality: 'Ultra'
  }
];
